"""Render each demo borrower's document pack as realistic PDFs.

The PDFs are fed through the *real* ingestion pipeline during seeding (no shortcuts), and are also
exported to demo/documents/ so reviewers can upload them by hand to watch extraction live.
"""

from __future__ import annotations

import io
import random
from datetime import date, timedelta
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from database.demo.portfolio import gstin_for
from utils.india import format_inr

BASE = ParagraphStyle("b", fontName="Helvetica", fontSize=9.5, leading=13)
SMALL = ParagraphStyle("s", parent=BASE, fontSize=8, leading=10, textColor=colors.HexColor("#555555"))
H1 = ParagraphStyle("h1", parent=BASE, fontName="Helvetica-Bold", fontSize=15, leading=19)
H2 = ParagraphStyle("h2", parent=BASE, fontName="Helvetica-Bold", fontSize=11, leading=15, spaceBefore=8, spaceAfter=4)
DEMO = "Fictional demonstration document generated by CredX — not a real company or filing."


def _pdf(story: list[Any], title: str) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=15 * mm, rightMargin=15 * mm, topMargin=15 * mm, bottomMargin=15 * mm,
                            title=title, author="CredX demo generator")
    doc.build(story)
    return buf.getvalue()


def _table(rows: list[list[str]], widths: list[float] | None = None, font_size: float = 8.5) -> Table:
    t = Table(rows, colWidths=widths, repeatRows=1)
    t.setStyle(TableStyle([
        ("FONT", (0, 0), (-1, -1), "Helvetica", font_size),
        ("FONT", (0, 0), (-1, 0), "Helvetica-Bold", font_size),
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e9eef6")),
        ("LINEBELOW", (0, 0), (-1, -1), 0.3, colors.HexColor("#c8d2e0")),
        ("ALIGN", (1, 0), (-1, -1), "RIGHT"),
    ]))
    return t


def _n(v: float) -> str:
    return f"{v:,.2f}"


def _rs(v: float) -> str:
    """Indian-grouped rupee amount with paise, no symbol: 12500000 -> 1,25,00,000.00"""
    return format_inr(round(v, 2), 2).replace("₹", "")


def annual_report(spec: dict[str, Any]) -> bytes:
    c, fin = spec["company"], spec["financials"]
    fy25, fy24, fy23 = fin["FY25"], fin["FY24"], fin["FY23"]
    story: list[Any] = [
        Paragraph("ANNUAL REPORT 2024-25", H1), Paragraph(c["name"], H2),
        Paragraph(f"CIN: {c['cin']} · Registered office: {c['address']}", SMALL), Spacer(1, 8),
        Paragraph("Board of Directors report", H2),
        Paragraph(f"Revenue for FY25 was INR {fy25['revenue']:.0f} crore compared with INR {fy24['revenue']:.0f} crore in FY24.", BASE),
    ]
    for sentence in spec.get("red_flag_text", []) + spec.get("positive_text", []):
        story.append(Paragraph(sentence, BASE))
    story += [Spacer(1, 6), Paragraph("Directors", H2)]
    for p in c["promoters"]:
        story.append(Paragraph(f"{p['name']} (DIN: {p['din']}) — {p['role']}", BASE))
    story += [Spacer(1, 6), Paragraph(DEMO, SMALL), PageBreak()]

    story += [Paragraph("Statement of Profit and Loss for the year ended March 31, 2025", H2), Paragraph("(INR in crore)", SMALL)]
    pnl = [["Particulars", "FY25", "FY24"],
           ["Revenue from operations", _n(fy25["revenue"]), _n(fy24["revenue"])],
           ["EBITDA", _n(fy25["ebitda"]), _n(fy24["ebitda"])],
           ["Depreciation and amortisation expense", _n(fy25["depreciation"]), _n(fy24["depreciation"])],
           ["Finance costs", _n(fy25["interest_expense"]), _n(fy24["interest_expense"])],
           ["Profit before tax", _n(fy25["ebitda"] - fy25["depreciation"] - fy25["interest_expense"]),
            _n(fy24["ebitda"] - fy24["depreciation"] - fy24["interest_expense"])],
           ["Profit for the year", _n(fy25["pat"]), _n(fy24["pat"])]]
    story += [_table(pnl, [95 * mm, 40 * mm, 40 * mm]), Spacer(1, 10)]
    story += [Paragraph("Balance Sheet as at March 31, 2025", H2), Paragraph("(INR in crore)", SMALL)]
    bs = [["Particulars", "FY25", "FY24"]] + [
        [label, _n(fy25[key]), _n(fy24[key])] for label, key in [
            ("Total equity", "net_worth"), ("Long-term borrowings", "long_term_debt"), ("Short-term borrowings", "short_term_debt"),
            ("Current maturities of long-term debt", "current_portion_ltd"), ("Trade receivables", "receivables"),
            ("Inventories", "inventory"), ("Cash and cash equivalents", "cash"), ("Total current assets", "current_assets"),
            ("Trade payables", "payables"), ("Total current liabilities", "current_liabilities"), ("Total assets", "total_assets"),
        ]]
    story += [_table(bs, [95 * mm, 40 * mm, 40 * mm]), Spacer(1, 10)]
    story += [Paragraph("Cash Flow Statement (summary)", H2), Paragraph("(INR in crore)", SMALL),
              _table([["Particulars", "FY25", "FY24"], ["Net cash from operating activities", _n(fy25["operating_cash_flow"]),
                                                        _n(fy24["operating_cash_flow"])]], [95 * mm, 40 * mm, 40 * mm]),
              PageBreak(), Paragraph("Financial highlights", H2), Paragraph("(INR in crore)", SMALL)]
    hl = [["Particulars", "FY25", "FY24", "FY23"]] + [
        [label, _n(fy25[k]), _n(fy24[k]), _n(fy23[k])] for label, k in [
            ("Revenue from operations", "revenue"), ("EBITDA", "ebitda"), ("Profit for the year", "pat"),
            ("Total borrowings", "total_debt"), ("Total equity", "net_worth"), ("Finance costs", "interest_expense"),
            ("Total current assets", "current_assets"), ("Total current liabilities", "current_liabilities"),
            ("Trade receivables", "receivables")]]
    story += [_table(hl, [80 * mm, 32 * mm, 32 * mm, 32 * mm]), Spacer(1, 8), Paragraph(DEMO, SMALL)]
    return _pdf(story, f"Annual Report FY25 - {c['name']}")


def gst_returns(spec: dict[str, Any]) -> bytes:
    c, g = spec["company"], spec["gst"]
    story = [
        Paragraph("GST RETURNS ANNUAL SUMMARY — GSTR-1 / GSTR-3B / GSTR-2A", H1),
        Paragraph(f"Financial year 2024-25 · Legal name: {c['name']}", BASE),
        Paragraph(f"GSTIN: {gstin_for(spec)}", BASE), Spacer(1, 8),
        Paragraph(f"GSTR-1 turnover (outward supplies): INR {g['GSTR-1']:.1f} crore", BASE),
        Paragraph(f"GSTR-3B turnover: INR {g['GSTR-3B']:.1f} crore", BASE),
        Paragraph(f"GSTR-2A turnover: INR {g['GSTR-2A']:.1f} crore", BASE),
        Paragraph(f"Input tax credit claimed: INR {g['itc']:.1f} crore", BASE),
        Paragraph(f"Total tax paid: INR {g['tax']:.1f} crore", BASE),
        Paragraph(f"Due date: {g['due']}", BASE), Paragraph(f"Date of filing: {g['filed_on']}", BASE), Spacer(1, 6),
    ]
    for line in spec.get("gst_note") or ["Variance remained within internal tolerance limits.",
                                          "Input tax credit matched vendor filings with only minor timing adjustments.",
                                          "GST compliance remained regular during FY25."]:
        story.append(Paragraph(line, BASE))
    story += [Spacer(1, 8), Paragraph(DEMO, SMALL)]
    return _pdf(story, f"GST summary FY25 - {c['name']}")


def bank_statement(spec: dict[str, Any], seed: int) -> bytes:
    c, b = spec["company"], spec["bank"]
    rng = random.Random(seed)
    balance = b["opening"] * 1e7
    rows = [["Date", "Narration", "Debit", "Credit", "Balance"]]
    start = date(2024, 10, 1)
    bounces_left = b["bounces"]
    for m in range(6):
        month_start = date(start.year + (start.month - 1 + m) // 12, (start.month - 1 + m) % 12 + 1, 1)
        credit_total = b["monthly_credit"] * 1e7 * max(0.3, 1 + b["volatility"] * rng.uniform(-1.2, 1.2))
        n_credits = 4
        for i in range(n_credits):
            amt = credit_total / n_credits * rng.uniform(0.8, 1.2)
            party = rng.choice(b["customers"]).upper()
            balance += amt
            d = month_start + timedelta(days=2 + i * 7)
            rows.append([d.strftime("%d-%m-%Y"), f"NEFT CR/UTR{rng.randint(10**9, 10**10 - 1)}/{party}", "0.00", _rs(amt), _rs(balance)])
        debit_total = credit_total * rng.uniform(0.9, 1.02)
        for i, (label, share) in enumerate([("supplier", 0.62), ("SALARY BATCH/PAYROLL", 0.14), ("GST PAYMENT/CBIC", 0.1),
                                            ("TERM LOAN EMI/LOAN A/C", 0.08), ("RTGS DR/ELECTRICITY BOARD", 0.06)]):
            amt = min(debit_total * share, max(balance - 2e5, 0))
            if amt <= 0:
                continue
            narration = f"RTGS DR/UTR{rng.randint(10**9, 10**10 - 1)}/{rng.choice(b['suppliers']).upper()}" if label == "supplier" else label
            balance -= amt
            d = month_start + timedelta(days=5 + i * 5)
            rows.append([d.strftime("%d-%m-%Y"), narration, _rs(amt), "0.00", _rs(balance)])
        if bounces_left and m >= 3:
            balance -= 590
            rows.append([(month_start + timedelta(days=27)).strftime("%d-%m-%Y"),
                         f"CHQ RETURN INSUFFICIENT FUNDS/CHQ00{rng.randint(4000, 4999)}", "590.00", "0.00", _rs(balance)])
            bounces_left -= 1
    story = [
        Paragraph("STATEMENT OF ACCOUNT", H1), Paragraph(b["bank"], H2),
        Paragraph(f"Account name: {c['name']}", BASE),
        Paragraph(f"Account number: XXXXXXXX{b['account'][-4:]} · IFSC: DEMO0001234 · Type: Current / Cash Credit", BASE),
        Paragraph("Statement period: October 2024 to March 2025", BASE),
        Paragraph(f"Opening balance: INR {b['opening']:.2f} crore", BASE),
        Paragraph(f"Closing balance: INR {balance / 1e7:.2f} crore", BASE), Spacer(1, 6),
        _table(rows, [22 * mm, 88 * mm, 24 * mm, 24 * mm, 24 * mm], font_size=7),
    ]
    if spec["key"] == "nebula":
        story += [Spacer(1, 6), Paragraph("Branch remarks: Working capital utilization remained above sanctioned levels for 23 days.", BASE),
                  Paragraph("Negative cash flow was observed during February and March.", BASE)]
    story += [Spacer(1, 6), Paragraph(DEMO, SMALL)]
    return _pdf(story, f"Bank statement - {c['name']}")


def mca_filing(spec: dict[str, Any]) -> bytes:
    c = spec["company"]
    debt = spec["financials"]["FY25"]["total_debt"]
    lender = (spec.get("sanction") or {}).get("lender", "State Bank of India")
    story = [
        Paragraph("FORM MGT-7 — ANNUAL RETURN (EXTRACT)", H1), Paragraph("Ministry of Corporate Affairs — Registrar of Companies", BASE),
        Spacer(1, 6), Paragraph(f"Corporate identity number (CIN): {c['cin']}", BASE), Paragraph(f"Name of the company: {c['name']}", BASE),
        Paragraph(f"Registered office: {c['address']}", BASE), Paragraph("Company status: Active", BASE),
        Paragraph(f"Authorised capital: INR {max(10, round(spec['financials']['FY25']['net_worth'] * 0.4)):.0f} crore", BASE),
        Paragraph(f"Paid-up capital: INR {max(5, round(spec['financials']['FY25']['net_worth'] * 0.3)):.0f} crore", BASE),
        Spacer(1, 6), Paragraph("Directors and key managerial personnel", H2),
    ]
    for p in c["promoters"]:
        story.append(Paragraph(f"{p['name']} (DIN: {p['din']}) — {p['role']}", BASE))
    story += [Spacer(1, 6), Paragraph("Index of charges", H2),
              Paragraph(f"Charge ID 1004{abs(hash(c['name'])) % 100000:05d} — charge holder: {lender} — amount INR {debt:.0f} crore — status open", BASE)]
    if spec["key"] == "nebula":
        story.append(Paragraph("Note: Form AOC-4 (financial statements) for FY 2024-25 not filed as on date; annual filing pending.", BASE))
    else:
        story.append(Paragraph("All annual filings (AOC-4 and MGT-7) are up to date.", BASE))
    story += [Spacer(1, 8), Paragraph(DEMO, SMALL)]
    return _pdf(story, f"MGT-7 extract - {c['name']}")


def shareholding(spec: dict[str, Any]) -> bytes:
    c, s = spec["company"], spec["shareholding"]
    story = [
        Paragraph("SHAREHOLDING PATTERN as on 31-03-2025", H1), Paragraph(c["name"], H2),
        Paragraph("Category of shareholder", BASE),
        Paragraph(f"Promoter and promoter group: {s['promoter']:.2f}%", BASE),
        Paragraph(f"Public shareholding: {s['public']:.2f}%", BASE),
        Paragraph(f"Shares pledged or otherwise encumbered: {s['pledged']:.2f}% of promoter holding", BASE), Spacer(1, 6),
    ]
    rows = [["Shareholder", "No. of shares held", "% holding"]]
    for p in c["promoters"]:
        rows.append([p["name"], f"{int(p['shareholding_pct'] * 100000):,}", f"{p['shareholding_pct']:.2f}"])
    story += [_table(rows, [80 * mm, 50 * mm, 30 * mm]), Spacer(1, 8), Paragraph(DEMO, SMALL)]
    return _pdf(story, f"Shareholding pattern - {c['name']}")


def legal_notice(spec: dict[str, Any], notice: dict[str, Any]) -> bytes:
    story = [Paragraph(notice["title"], H1), Paragraph(f"Borrower: {spec['company']['name']}", BASE), Spacer(1, 6)]
    story += [Paragraph(line, BASE) for line in notice["body"]]
    story += [Spacer(1, 8), Paragraph("Issued without prejudice to the rights and remedies of the sender.", SMALL), Paragraph(DEMO, SMALL)]
    return _pdf(story, notice["title"])


def sanction_letter(spec: dict[str, Any]) -> bytes:
    s, c = spec["sanction"], spec["company"]
    story = [Paragraph("SANCTION LETTER", H1), Paragraph(s["lender"], H2), Paragraph(f"To: {c['name']}", BASE), Spacer(1, 4),
             Paragraph("We are pleased to inform you that the following credit facilities have been sanctioned, subject to the terms and conditions of sanction below.", BASE)]
    for name, limit in s["facilities"]:
        story.append(Paragraph(f"{name} facility — sanctioned limit INR {limit:.0f} crore", BASE))
    story += [Paragraph(f"Rate of interest: {s['rate']:.2f}% p.a. (EBLR + {s['rate'] - 9.25:.2f}%)", BASE),
              Paragraph("Tenure: 60 months for term loan; working capital renewable annually.", BASE),
              Paragraph("Primary security: hypothecation of stocks and book debts; plant and machinery.", BASE),
              Paragraph("Collateral security: equitable mortgage of factory land and building.", BASE),
              Paragraph("Covenant: the borrower shall maintain DSCR of at least 1.25x and TOL/TNW below 3.0x.", BASE),
              Paragraph("Covenant: the borrower shall not create further charge on the secured assets without prior consent.", BASE),
              Spacer(1, 8), Paragraph(DEMO, SMALL)]
    return _pdf(story, f"Sanction letter - {c['name']}")


def document_pack(spec: dict[str, Any], seed: int = 7) -> list[tuple[str, bytes]]:
    pack = [
        ("annual_report_FY25.pdf", annual_report(spec)),
        ("gst_returns_FY25.pdf", gst_returns(spec)),
        ("bank_statement_Oct24-Mar25.pdf", bank_statement(spec, seed)),
        ("mca_mgt7_extract.pdf", mca_filing(spec)),
        ("shareholding_pattern.pdf", shareholding(spec)),
    ]
    if spec.get("sanction"):
        pack.append(("existing_sanction_letter.pdf", sanction_letter(spec)))
    for i, notice in enumerate(spec.get("legal") or [], 1):
        pack.append((f"legal_notice_{i}.pdf", legal_notice(spec, notice)))
    return pack
