"""Editable DOCX export of a CAM document (python-docx)."""

from __future__ import annotations

import io
from typing import Any

from docx import Document
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Pt, RGBColor

from ..formatting.formatters import date

NAVY = RGBColor(0x0B, 0x25, 0x45)
MUTED = RGBColor(0x5B, 0x6B, 0x82)
TONE = {"positive": RGBColor(0x0F, 0x7B, 0x4C), "warning": RGBColor(0xA1, 0x5C, 0x00),
        "negative": RGBColor(0xB4, 0x23, 0x18), "neutral": NAVY}


def _shade(cell, hex_fill: str) -> None:  # type: ignore[no-untyped-def]
    props = cell._tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"), hex_fill)
    props.append(shd)


def _table(doc, columns: list[str], rows: list[list[str]]) -> None:  # type: ignore[no-untyped-def]
    t = doc.add_table(rows=1, cols=len(columns))
    t.style = "Table Grid"
    t.alignment = WD_TABLE_ALIGNMENT.CENTER
    for i, col in enumerate(columns):
        cell = t.rows[0].cells[i]
        cell.text = ""
        run = cell.paragraphs[0].add_run(col)
        run.bold, run.font.size, run.font.color.rgb = True, Pt(8.5), RGBColor(0xFF, 0xFF, 0xFF)
        _shade(cell, "0B2545")
    for row in rows:
        cells = t.add_row().cells
        for i, value in enumerate(row):
            cells[i].text = ""
            cells[i].paragraphs[0].add_run(str(value)).font.size = Pt(8.5)
    doc.add_paragraph()


def render_docx(cam: dict[str, Any]) -> bytes:
    doc = Document()
    normal = doc.styles["Normal"]
    normal.font.name, normal.font.size = "Calibri", Pt(10)

    title = doc.add_heading(cam["title"], level=0)
    for run in title.runs:
        run.font.color.rgb = NAVY
    meta = doc.add_paragraph()
    run = meta.add_run(f"Reference {cam.get('reference')} · Prepared {date(cam.get('generated_at'))}"
                       + (f" · Analyst: {cam['prepared_by']}" if cam.get("prepared_by") else "") + " · CONFIDENTIAL")
    run.font.size, run.font.color.rgb = Pt(9), MUTED

    head = cam.get("headline") or {}
    if head.get("credit_score"):
        _table(doc, ["CredX score", "Grade", "Risk", "PD", "Recommended", "Rate"], [[
            str(head["credit_score"]), head.get("grade") or "—", (head.get("risk_level") or "—").title(),
            f"{(head.get('pd') or 0):.2%}", f"₹{(head.get('amount') or 0) / 1e7:,.2f} Cr", f"{head.get('rate') or 0:.2f}%",
        ]])

    for section in cam["sections"]:
        h = doc.add_heading(section["title"], level=1)
        for r in h.runs:
            r.font.color.rgb = NAVY
        for block in section["blocks"]:
            kind = block["type"]
            if kind == "paragraph" and block.get("text"):
                doc.add_paragraph(block["text"])
            elif kind == "heading":
                doc.add_heading(block["text"], level=3)
            elif kind == "bullets":
                for item in block["items"]:
                    doc.add_paragraph(item, style="List Bullet")
            elif kind == "table" and block["rows"]:
                if block.get("caption"):
                    cap = doc.add_paragraph().add_run(block["caption"])
                    cap.italic, cap.font.size, cap.font.color.rgb = True, Pt(8.5), MUTED
                _table(doc, block["columns"], block["rows"])
            elif kind == "kv":
                _table(doc, ["Particular", "Detail"], [[i["label"], i["value"]] for i in block["items"]])
            elif kind == "callout":
                para = doc.add_paragraph()
                r = para.add_run(block["title"] + " — ")
                r.bold, r.font.color.rgb = True, TONE.get(block.get("tone", "neutral"), NAVY)
                para.add_run(block.get("text", ""))
        if section.get("analyst_comment"):
            c = doc.add_paragraph().add_run(f"Analyst comment: {section['analyst_comment']}")
            c.italic, c.font.color.rgb = True, MUTED

    foot = doc.add_paragraph().add_run(
        "Generated by CredX. All recommendations are subject to sanctioning-authority approval under the lender's credit policy."
    )
    foot.italic, foot.font.size, foot.font.color.rgb = True, Pt(8), MUTED
    buffer = io.BytesIO()
    doc.save(buffer)
    return buffer.getvalue()
