"""initial schema

Revision ID: 5e886f5e16b2
Revises: 
Create Date: 2026-10-04 19:51:40.802706
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '5e886f5e16b2'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_usage',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_usage'))
    )
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_usage_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_provider'), ['provider'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('audit_logs',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cin', sa.String(length=21), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('sector', sa.String(length=80), nullable=True),
    sa.Column('sub_sector', sa.String(length=120), nullable=True),
    sa.Column('constitution', sa.String(length=60), nullable=True),
    sa.Column('incorporation_year', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('promoters', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('external_rating', sa.String(length=40), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_companies_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies')),
    sa.UniqueConstraint('cin', name=op.f('uq_companies_cin'))
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_gstin'), ['gstin'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_pan'), ['pan'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_sector'), ['sector'], unique=False)

    op.create_table('credit_cases',
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('facility_type', sa.String(length=60), nullable=False),
    sa.Column('requested_amount', sa.Float(), nullable=False),
    sa.Column('tenure_months', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('collateral_type', sa.String(length=120), nullable=True),
    sa.Column('collateral_value', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('assigned_to_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('final_decision', sa.String(length=32), nullable=True),
    sa.Column('decided_by_id', sa.String(length=36), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_rationale', sa.Text(), nullable=True),
    sa.Column('latest_score', sa.Integer(), nullable=True),
    sa.Column('latest_risk_level', sa.String(length=16), nullable=True),
    sa.Column('latest_fraud_score', sa.Integer(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('network', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_credit_cases_assigned_to_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_credit_cases_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_credit_cases_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], name=op.f('fk_credit_cases_decided_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_cases'))
    )
    with op.batch_alter_table('credit_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_cases_assigned_to_id'), ['assigned_to_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_cases_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_cases_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_cases_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_credit_cases_status'), ['status'], unique=False)

    op.create_table('analyst_notes',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=True),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('impact_points', sa.Integer(), nullable=True),
    sa.Column('inferred_impact', sa.Integer(), nullable=True),
    sa.Column('impact_rationale', sa.Text(), nullable=True),
    sa.Column('five_c', sa.String(length=16), nullable=True),
    sa.Column('include_in_cam', sa.Boolean(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_analyst_notes_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['credit_cases.id'], name=op.f('fk_analyst_notes_case_id_credit_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['analyst_notes.id'], name=op.f('fk_analyst_notes_parent_id_analyst_notes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analyst_notes'))
    )
    with op.batch_alter_table('analyst_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyst_notes_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyst_notes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyst_notes_parent_id'), ['parent_id'], unique=False)

    op.create_table('copilot_messages',
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('citations', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['credit_cases.id'], name=op.f('fk_copilot_messages_case_id_credit_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_copilot_messages_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_copilot_messages'))
    )
    with op.batch_alter_table('copilot_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_copilot_messages_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_copilot_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_copilot_messages_user_id'), ['user_id'], unique=False)

    op.create_table('credit_scores',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('model_score', sa.Integer(), nullable=False),
    sa.Column('credit_score', sa.Integer(), nullable=False),
    sa.Column('probability_of_default', sa.Float(), nullable=False),
    sa.Column('approval_probability', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('rating', sa.String(length=8), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('recommended_amount', sa.Float(), nullable=False),
    sa.Column('suggested_rate', sa.Float(), nullable=False),
    sa.Column('features', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('contributions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('overlays', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('policy', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('five_cs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('loan_sizing', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('pricing', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ratios', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('top_risk_factors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('top_strengths', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('explanation', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['credit_cases.id'], name=op.f('fk_credit_scores_case_id_credit_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_credit_scores_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_scores'))
    )
    with op.batch_alter_table('credit_scores', schema=None) as batch_op:
        batch_op.create_index('ix_credit_scores_case_version', ['case_id', 'version'], unique=True)
        batch_op.create_index(batch_op.f('ix_credit_scores_created_at'), ['created_at'], unique=False)

    op.create_table('documents',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=80), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('declared_type', sa.String(length=40), nullable=True),
    sa.Column('doc_type', sa.String(length=40), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('classification_signals', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('ocr_used', sa.Boolean(), nullable=False),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('extracted', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('text_preview', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('uploaded_by_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['credit_cases.id'], name=op.f('fk_documents_case_id_credit_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_documents_uploaded_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('case_id', 'sha256', name='uq_documents_case_sha')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_doc_type'), ['doc_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_status'), ['status'], unique=False)

    op.create_table('escalations',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('raised_by_id', sa.String(length=36), nullable=True),
    sa.Column('to_role', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_by_id', sa.String(length=36), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['credit_cases.id'], name=op.f('fk_escalations_case_id_credit_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raised_by_id'], ['users.id'], name=op.f('fk_escalations_raised_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], name=op.f('fk_escalations_resolved_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_escalations'))
    )
    with op.batch_alter_table('escalations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_escalations_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_escalations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_escalations_status'), ['status'], unique=False)

    op.create_table('fraud_analyses',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('fraud_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('graph', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('heatmap', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('gst_checks', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('stats', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['credit_cases.id'], name=op.f('fk_fraud_analyses_case_id_credit_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fraud_analyses'))
    )
    with op.batch_alter_table('fraud_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fraud_analyses_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fraud_analyses_created_at'), ['created_at'], unique=False)

    op.create_table('manual_overrides',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('field', sa.String(length=32), nullable=False),
    sa.Column('original_value', sa.String(length=80), nullable=True),
    sa.Column('new_value', sa.String(length=80), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('requested_by_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_by_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['credit_cases.id'], name=op.f('fk_manual_overrides_case_id_credit_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_manual_overrides_requested_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], name=op.f('fk_manual_overrides_reviewed_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manual_overrides'))
    )
    with op.batch_alter_table('manual_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_manual_overrides_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_manual_overrides_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_manual_overrides_status'), ['status'], unique=False)

    op.create_table('research_reports',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('litigation_risk', sa.String(length=16), nullable=False),
    sa.Column('promoter_sentiment', sa.String(length=16), nullable=False),
    sa.Column('sector_outlook', sa.String(length=16), nullable=False),
    sa.Column('overall_risk', sa.String(length=16), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('litigation_score', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('sector', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('mca', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('providers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('queries', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['credit_cases.id'], name=op.f('fk_research_reports_case_id_credit_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_reports'))
    )
    with op.batch_alter_table('research_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_reports_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_reports_created_at'), ['created_at'], unique=False)

    op.create_table('bank_statement_summaries',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('bank_name', sa.String(length=120), nullable=True),
    sa.Column('account_masked', sa.String(length=32), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('opening_balance', sa.Float(), nullable=True),
    sa.Column('closing_balance', sa.Float(), nullable=True),
    sa.Column('total_credits', sa.Float(), nullable=True),
    sa.Column('total_debits', sa.Float(), nullable=True),
    sa.Column('average_balance', sa.Float(), nullable=True),
    sa.Column('bounce_count', sa.Integer(), nullable=False),
    sa.Column('overdraw_days', sa.Integer(), nullable=False),
    sa.Column('monthly', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('counterparties', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['credit_cases.id'], name=op.f('fk_bank_statement_summaries_case_id_credit_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_bank_statement_summaries_document_id_documents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_statement_summaries'))
    )
    with op.batch_alter_table('bank_statement_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_statement_summaries_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_statement_summaries_created_at'), ['created_at'], unique=False)

    op.create_table('cam_reports',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('score_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('sections', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('analyst_comments', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('html', sa.Text(), nullable=True),
    sa.Column('pdf_key', sa.String(length=512), nullable=True),
    sa.Column('docx_key', sa.String(length=512), nullable=True),
    sa.Column('narrative_provider', sa.String(length=32), nullable=True),
    sa.Column('generated_by_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['credit_cases.id'], name=op.f('fk_cam_reports_case_id_credit_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], name=op.f('fk_cam_reports_generated_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['score_id'], ['credit_scores.id'], name=op.f('fk_cam_reports_score_id_credit_scores'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cam_reports'))
    )
    with op.batch_alter_table('cam_reports', schema=None) as batch_op:
        batch_op.create_index('ix_cam_reports_case_version', ['case_id', 'version'], unique=True)
        batch_op.create_index(batch_op.f('ix_cam_reports_created_at'), ['created_at'], unique=False)

    op.create_table('financial_statements',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('fiscal_year', sa.String(length=8), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('ebitda', sa.Float(), nullable=True),
    sa.Column('depreciation', sa.Float(), nullable=True),
    sa.Column('interest_expense', sa.Float(), nullable=True),
    sa.Column('pat', sa.Float(), nullable=True),
    sa.Column('total_debt', sa.Float(), nullable=True),
    sa.Column('short_term_debt', sa.Float(), nullable=True),
    sa.Column('long_term_debt', sa.Float(), nullable=True),
    sa.Column('current_portion_ltd', sa.Float(), nullable=True),
    sa.Column('current_assets', sa.Float(), nullable=True),
    sa.Column('current_liabilities', sa.Float(), nullable=True),
    sa.Column('total_assets', sa.Float(), nullable=True),
    sa.Column('net_worth', sa.Float(), nullable=True),
    sa.Column('receivables', sa.Float(), nullable=True),
    sa.Column('inventory', sa.Float(), nullable=True),
    sa.Column('payables', sa.Float(), nullable=True),
    sa.Column('cash', sa.Float(), nullable=True),
    sa.Column('operating_cash_flow', sa.Float(), nullable=True),
    sa.Column('contingent_liabilities', sa.Float(), nullable=True),
    sa.Column('related_party_transactions', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('provenance', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['credit_cases.id'], name=op.f('fk_financial_statements_case_id_credit_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_financial_statements_document_id_documents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_statements')),
    sa.UniqueConstraint('case_id', 'fiscal_year', name='uq_financials_case_fy')
    )
    with op.batch_alter_table('financial_statements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_statements_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_statements_created_at'), ['created_at'], unique=False)

    op.create_table('fraud_alerts',
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('alert_type', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('entities', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('score_impact', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['fraud_analyses.id'], name=op.f('fk_fraud_alerts_analysis_id_fraud_analyses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['credit_cases.id'], name=op.f('fk_fraud_alerts_case_id_credit_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fraud_alerts'))
    )
    with op.batch_alter_table('fraud_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fraud_alerts_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_fraud_alerts_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index('ix_fraud_alerts_case_status', ['case_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_fraud_alerts_created_at'), ['created_at'], unique=False)

    op.create_table('gst_filings',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('return_type', sa.String(length=12), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('taxable_turnover', sa.Float(), nullable=True),
    sa.Column('tax_paid', sa.Float(), nullable=True),
    sa.Column('itc_claimed', sa.Float(), nullable=True),
    sa.Column('filed_on', sa.Date(), nullable=True),
    sa.Column('days_late', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['credit_cases.id'], name=op.f('fk_gst_filings_case_id_credit_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_gst_filings_document_id_documents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gst_filings'))
    )
    with op.batch_alter_table('gst_filings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gst_filings_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gst_filings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_gst_filings_gstin'), ['gstin'], unique=False)

    op.create_table('jobs',
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('steps', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('backend', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['credit_cases.id'], name=op.f('fk_jobs_case_id_credit_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_jobs_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_jobs_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['jobs.id'], name=op.f('fk_jobs_parent_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_case_kind', ['case_id', 'kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('research_findings',
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=160), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sentiment', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['credit_cases.id'], name=op.f('fk_research_findings_case_id_credit_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['research_reports.id'], name=op.f('fk_research_findings_report_id_research_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_findings'))
    )
    with op.batch_alter_table('research_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_findings_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_findings_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_findings_report_id'), ['report_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_findings_report_id'))
        batch_op.drop_index(batch_op.f('ix_research_findings_category'))
        batch_op.drop_index(batch_op.f('ix_research_findings_case_id'))

    op.drop_table('research_findings')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_parent_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_kind'))
        batch_op.drop_index(batch_op.f('ix_jobs_created_at'))
        batch_op.drop_index('ix_jobs_case_kind')

    op.drop_table('jobs')
    with op.batch_alter_table('gst_filings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gst_filings_gstin'))
        batch_op.drop_index(batch_op.f('ix_gst_filings_created_at'))
        batch_op.drop_index(batch_op.f('ix_gst_filings_case_id'))

    op.drop_table('gst_filings')
    with op.batch_alter_table('fraud_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fraud_alerts_created_at'))
        batch_op.drop_index('ix_fraud_alerts_case_status')
        batch_op.drop_index(batch_op.f('ix_fraud_alerts_analysis_id'))
        batch_op.drop_index(batch_op.f('ix_fraud_alerts_alert_type'))

    op.drop_table('fraud_alerts')
    with op.batch_alter_table('financial_statements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_statements_created_at'))
        batch_op.drop_index(batch_op.f('ix_financial_statements_case_id'))

    op.drop_table('financial_statements')
    with op.batch_alter_table('cam_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cam_reports_created_at'))
        batch_op.drop_index('ix_cam_reports_case_version')

    op.drop_table('cam_reports')
    with op.batch_alter_table('bank_statement_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_statement_summaries_created_at'))
        batch_op.drop_index(batch_op.f('ix_bank_statement_summaries_case_id'))

    op.drop_table('bank_statement_summaries')
    with op.batch_alter_table('research_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_reports_created_at'))
        batch_op.drop_index(batch_op.f('ix_research_reports_case_id'))

    op.drop_table('research_reports')
    with op.batch_alter_table('manual_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_manual_overrides_status'))
        batch_op.drop_index(batch_op.f('ix_manual_overrides_created_at'))
        batch_op.drop_index(batch_op.f('ix_manual_overrides_case_id'))

    op.drop_table('manual_overrides')
    with op.batch_alter_table('fraud_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fraud_analyses_created_at'))
        batch_op.drop_index(batch_op.f('ix_fraud_analyses_case_id'))

    op.drop_table('fraud_analyses')
    with op.batch_alter_table('escalations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_escalations_status'))
        batch_op.drop_index(batch_op.f('ix_escalations_created_at'))
        batch_op.drop_index(batch_op.f('ix_escalations_case_id'))

    op.drop_table('escalations')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_status'))
        batch_op.drop_index(batch_op.f('ix_documents_sha256'))
        batch_op.drop_index(batch_op.f('ix_documents_doc_type'))
        batch_op.drop_index(batch_op.f('ix_documents_created_at'))
        batch_op.drop_index(batch_op.f('ix_documents_case_id'))

    op.drop_table('documents')
    with op.batch_alter_table('credit_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_scores_created_at'))
        batch_op.drop_index('ix_credit_scores_case_version')

    op.drop_table('credit_scores')
    with op.batch_alter_table('copilot_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_copilot_messages_user_id'))
        batch_op.drop_index(batch_op.f('ix_copilot_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_copilot_messages_case_id'))

    op.drop_table('copilot_messages')
    with op.batch_alter_table('analyst_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyst_notes_parent_id'))
        batch_op.drop_index(batch_op.f('ix_analyst_notes_created_at'))
        batch_op.drop_index(batch_op.f('ix_analyst_notes_case_id'))

    op.drop_table('analyst_notes')
    with op.batch_alter_table('credit_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_cases_status'))
        batch_op.drop_index(batch_op.f('ix_credit_cases_reference'))
        batch_op.drop_index(batch_op.f('ix_credit_cases_created_at'))
        batch_op.drop_index(batch_op.f('ix_credit_cases_company_id'))
        batch_op.drop_index(batch_op.f('ix_credit_cases_assigned_to_id'))

    op.drop_table('credit_cases')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_sector'))
        batch_op.drop_index(batch_op.f('ix_companies_pan'))
        batch_op.drop_index(batch_op.f('ix_companies_name'))
        batch_op.drop_index(batch_op.f('ix_companies_gstin'))
        batch_op.drop_index(batch_op.f('ix_companies_created_at'))

    op.drop_table('companies')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_entity')
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_case_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_usage_provider'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_created_at'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_case_id'))

    op.drop_table('ai_usage')
    # ### end Alembic commands ###
